# Generated by Django 5.0.1 on 2024-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_category',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('International', 'International')], default='Local', max_length=20, null=True),
        ),
    ]
